version: "3"

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go
  test:
    cmds:
      - go test -v ./...
  lint:
    cmds:
      - golangci-lint run
  run:
    cmds:
      - docker-compose up --build

  integration-tests:
    cmds:
      - docker-compose -f docker-compose-for-tests.yml up -d db
      - cat migrations/0001_init_schema.down.sql | docker exec -i nectar-sql-db-for-tests psql -U postgres -d postgres
      - cat migrations/0001_init_schema.up.sql | docker exec -i nectar-sql-db-for-tests psql -U postgres -d postgres
      - go test -tags=integration -v ./...
      - docker-compose down

    env:
      DB_USERNAME: postgres
      DB_PASSWORD: pgpassword
      DB_TABLE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DB: postgres
      SSL_MODE: disable
      TOKEN_SECRET: nectar

  acceptance_tests:
    cmds:
      - docker-compose -f docker-compose-for-tests.yml up -d
      - cat migrations/0001_init_schema.down.sql | docker exec -i nectar-sql-db-for-tests psql -U postgres -d postgres
      - cat migrations/0001_init_schema.up.sql | docker exec -i nectar-sql-db-for-tests psql -U postgres -d postgres
      - go test -tags=e2e -v ./...
      - docker-compose down
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: pgpassword
      DB_TABLE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DB: postgres
      SSL_MODE: disable
      TOKEN_SECRET: nectar